# Generated by Django 4.0 on 2022-01-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='img',
        ),
    ]
